Fix compilation error on mac, missing import.
Forward declaration of a template type would not build for me on Mac.

Error:

```
In file included from src/map/battlefield.cpp:24:
src/map/battlefield.h:176:35: error: implicit instantiation of undefined
      template 'std::__1::vector<BattlefieldMob_t,
      std::__1::allocator<BattlefieldMob_t> >'
    std::vector<BattlefieldMob_t> m_RequiredEnemyList;
                                  ^
```

This is remedied by `#include <vector>` explicitly.